[package]
name = "waybar-dbus-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
zbus = "5.7.1"
futures-util = "0.3"
